version: '3'

volumes:
  mysql:

services:
  docker-for-wordpress:
    image: wordpress:4.9.7-php7.0-apache
    container_name: docker-for-wordpress
    ports:
      - 127.0.0.1:8000:80
    env_file: .env
    volumes:
      - ./wp:/var/www/html
    depends_on:
      - docker-for-wordpress-mysql

  docker-for-wordpress-mysql:
    image: mysql:5.7
    container_name: docker-for-wordpress-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    env_file: .env